export const CREATE_UPDATE_POST_REQUEST = "CREATE_UPDATE_POST_REQUEST";
export const CREATE_UPDATE_POST_SUCCESS = "CREATE_UPDATE_POST_SUCCESS";
export const CREATE_UPDATE_POST_RESET = "CREATE_UPDATE_POST_RESET";
export const CREATE_UPDATE_POST_FAIL = "CREATE_UPDATE_POST_FAIL";

export const ALL_UPDATE_POST_REQUEST = "ALL_UPDATE_POST_REQUEST";
export const ALL_UPDATE_POST_SUCCESS = "ALL_UPDATE_POST_SUCCESS";
export const ALL_UPDATE_POST_FAIL = "ALL_UPDATE_POST_FAIL";


export const CLEAR_ERRORS = "CLEAR_ERRORS";
