export const ALL_POST_REQUEST = "ALL_POST_REQUEST";
export const ALL_POST_SUCCESS = "ALL_POST_SUCCESS";
export const ALL_POST_FAIL = "ALL_POST_FAIL";

export const OPEN_SPECIFIC_POST_REQUEST = "OPEN_SPECIFIC_POST_REQUEST";
export const OPEN_SPECIFIC_POST_SUCCESS = "OPEN_SPECIFIC_POST_SUCCESS";
export const OPEN_SPECIFIC_POST_FAIL = "OPEN_SPECIFIC_POST_FAIL";

export const CREATE_POST_REQUEST = "CREATE_POST_REQUEST";
export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_RESET = "CREATE_POST_RESET";
export const CREATE_POST_FAIL = "CREATE_POST_FAIL";

export const COMMENT_REQUEST = "COMMENT_REQUEST";
export const COMMENT_SUCCESS = "COMMENT_SUCCESS";
export const COMMENT_FAIL = "COMMENT_FAIL";
export const COMMENT_RESET = "COMMENT_RESET";

export const DELETE_POST_REQUEST = "DELETE_POST_REQUEST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_RESET = "DELETE_POST_RESET";
export const DELETE_POST_FAIL = "DELETE_POST_FAIL";

export const LIKE_POST_REQUEST = "LIKE_POST_REQUEST";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const LIKE_POST_FAIL = "LIKE_POST_FAIL"; 

export const TREND_GET_REQUEST = "TREND_GET_REQUEST";
export const TREND_GET_SUCCESS = "TREND_GET_SUCCESS";
export const TREND_GET_FAIL = "TREND_GET_FAIL"; 

export const TREND_POST_REQUEST = "TREND_POST_REQUEST";
export const TREND_POST_SUCCESS = "TREND_POST_SUCCESS";
export const TREND_POST_FAIL = "TREND_POST_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";